// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: WE_GPC_UnoR4Display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t *ui_HomeScreen;
lv_obj_t *ui_Chart1;
lv_obj_t *ui_Label1;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label2;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Label31;
lv_obj_t *ui_Label32;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t *ui_SettingsScreen;
lv_obj_t *ui_Label33;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Roller3;
lv_obj_t *ui_Label35;
lv_obj_t *ui_Label36;
lv_obj_t *ui_Label37;
lv_obj_t *ui_Label38;
lv_obj_t *ui_Label39;
lv_obj_t *ui_Roller1;
lv_obj_t *ui_Label40;
lv_obj_t *ui_Label41;
lv_obj_t *ui_Label42;
lv_obj_t *ui_Slider1;
lv_obj_t *ui_Label43;
lv_obj_t *ui_Button7;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Roller2;
lv_obj_t *ui_Checkbox1;


// SCREEN: ui_ProfilesScreen
void ui_ProfilesScreen_screen_init(void);
lv_obj_t *ui_ProfilesScreen;
lv_obj_t *ui_Panel2;
void ui_event_Panel3( lv_event_t * e);
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label47;
void ui_event_Panel4( lv_event_t * e);
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label49;
void ui_event_Panel5( lv_event_t * e);
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Label50;
void ui_event_Panel6( lv_event_t * e);
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label56;
void ui_event_Panel7( lv_event_t * e);
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Label57;
void ui_event_Panel8( lv_event_t * e);
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Label58;
void ui_event_Panel9( lv_event_t * e);
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Label59;
void ui_event_Panel10( lv_event_t * e);
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Label60;
void ui_event_Panel11( lv_event_t * e);
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Label61;
void ui_event_Panel12( lv_event_t * e);
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Label62;
void ui_event_Panel13( lv_event_t * e);
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Label63;
void ui_event_Panel14( lv_event_t * e);
lv_obj_t *ui_Panel14;
lv_obj_t *ui_Label64;
void ui_event_Panel15( lv_event_t * e);
lv_obj_t *ui_Panel15;
lv_obj_t *ui_Label65;
void ui_event_Panel16( lv_event_t * e);
lv_obj_t *ui_Panel16;
lv_obj_t *ui_Label66;
void ui_event_Panel17( lv_event_t * e);
lv_obj_t *ui_Panel17;
lv_obj_t *ui_Label67;
lv_obj_t *ui_Label48;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label68;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label6;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ProfilesScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_ProfilesScreen_screen_init);
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_SettingsScreen_screen_init);
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_HomeScreen_screen_init);
}
}
void ui_event_Panel3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "EMP");
      _ui_checked_set_text_value( ui_Label1, target, "", "EMP");
}
}
void ui_event_Panel4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "3-6-9");
      _ui_checked_set_text_value( ui_Label1, target, "", "3-6-9");
}
}
void ui_event_Panel5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Extractamundo-dos!");
      _ui_checked_set_text_value( ui_Label1, target, "", "Extractamundo-dos!");
}
}
void ui_event_Panel6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Flat 6");
      _ui_checked_set_text_value( ui_Label1, target, "", "Flat 6");
}
}
void ui_event_Panel7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Slayer 6");
      _ui_checked_set_text_value( ui_Label1, target, "", "Slayer 6");
}
}
void ui_event_Panel8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "WE Pro 6");
      _ui_checked_set_text_value( ui_Label1, target, "", "WE Pro 6");
}
}
void ui_event_Panel9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Flat 9");
      _ui_checked_set_text_value( ui_Label1, target, "", "Flat 9");
}
}
void ui_event_Panel10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Slayer 9");
      _ui_checked_set_text_value( ui_Label1, target, "", "Slayer 9");
}
}
void ui_event_Panel11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "WE Pro 9");
      _ui_checked_set_text_value( ui_Label1, target, "", "WE Pro 9");
}
}
void ui_event_Panel12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Londinium");
      _ui_checked_set_text_value( ui_Label1, target, "", "Londinium");
}
}
void ui_event_Panel13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Leva X");
      _ui_checked_set_text_value( ui_Label1, target, "", "Leva X");
}
}
void ui_event_Panel14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Cremina");
      _ui_checked_set_text_value( ui_Label1, target, "", "Cremina");
}
}
void ui_event_Panel15( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Turbo");
      _ui_checked_set_text_value( ui_Label1, target, "", "Turbo");
}
}
void ui_event_Panel16( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Blooming");
      _ui_checked_set_text_value( ui_Label1, target, "", "Blooming");
}
}
void ui_event_Panel17( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_Label48, target, "", "Spro-Over");
      _ui_checked_set_text_value( ui_Label1, target, "", "Spro-Over");
}
}
void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_HomeScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_HomeScreen_screen_init();
ui_SettingsScreen_screen_init();
ui_ProfilesScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_HomeScreen);
}
