// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: WE_GPC_UnoR4Display

#ifndef _WE_GPC_UNOR4DISPLAY_UI_H
#define _WE_GPC_UNOR4DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_Label1;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label2;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_Label32;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t *ui_SettingsScreen;
extern lv_obj_t *ui_Label33;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Roller3;
extern lv_obj_t *ui_Label35;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_Label37;
extern lv_obj_t *ui_Label38;
extern lv_obj_t *ui_Label39;
extern lv_obj_t *ui_Roller1;
extern lv_obj_t *ui_Label40;
extern lv_obj_t *ui_Label41;
extern lv_obj_t *ui_Label42;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Label43;
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Checkbox1;
// SCREEN: ui_ProfilesScreen
void ui_ProfilesScreen_screen_init(void);
extern lv_obj_t *ui_ProfilesScreen;
extern lv_obj_t *ui_Panel2;
void ui_event_Panel3( lv_event_t * e);
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label47;
void ui_event_Panel4( lv_event_t * e);
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label49;
void ui_event_Panel5( lv_event_t * e);
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label50;
void ui_event_Panel6( lv_event_t * e);
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label56;
void ui_event_Panel7( lv_event_t * e);
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label57;
void ui_event_Panel8( lv_event_t * e);
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label58;
void ui_event_Panel9( lv_event_t * e);
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Label59;
void ui_event_Panel10( lv_event_t * e);
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Label60;
void ui_event_Panel11( lv_event_t * e);
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Label61;
void ui_event_Panel12( lv_event_t * e);
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Label62;
void ui_event_Panel13( lv_event_t * e);
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Label63;
void ui_event_Panel14( lv_event_t * e);
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_Label64;
void ui_event_Panel15( lv_event_t * e);
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_Label65;
void ui_event_Panel16( lv_event_t * e);
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Label66;
void ui_event_Panel17( lv_event_t * e);
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Label67;
extern lv_obj_t *ui_Label48;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label68;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_espressoprofilepic_png);   // assets/EspressoProfilePic.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
