// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: WE_GPC_UnoR4Display

#include "ui.h"

void ui_ProfilesScreen_screen_init(void)
{
ui_ProfilesScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ProfilesScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ProfilesScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ProfilesScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ProfilesScreen, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ProfilesScreen, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_ProfilesScreen);
lv_obj_set_width( ui_Panel2, 420);
lv_obj_set_height( ui_Panel2, 480);
lv_obj_set_x( ui_Panel2, -200 );
lv_obj_set_y( ui_Panel2, 0 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel3, 120);
lv_obj_set_height( ui_Panel3, 80);
lv_obj_set_x( ui_Panel3, -130 );
lv_obj_set_y( ui_Panel3, -190 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel3, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel3, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel3, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel3, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel3, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label47 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label47, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label47, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label47, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label47,"EMP");
lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel4, 120);
lv_obj_set_height( ui_Panel4, 80);
lv_obj_set_x( ui_Panel4, 5 );
lv_obj_set_y( ui_Panel4, -190 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel4, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel4, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel4, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel4, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel4, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label49 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label49, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label49, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label49, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label49,"3-6-9");
lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel5, 120);
lv_obj_set_height( ui_Panel5, 80);
lv_obj_set_x( ui_Panel5, 140 );
lv_obj_set_y( ui_Panel5, -190 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel5, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel5, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel5, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel5, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel5, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel5, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel5, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel5, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label50 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label50, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label50, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label50, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label50,"Extract-2!");
lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel6, 120);
lv_obj_set_height( ui_Panel6, 80);
lv_obj_set_x( ui_Panel6, -130 );
lv_obj_set_y( ui_Panel6, -95 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel6, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel6, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel6, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel6, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel6, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel6, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel6, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel6, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel6, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label56 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label56, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label56, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label56, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label56,"Flat 6");
lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel7, 120);
lv_obj_set_height( ui_Panel7, 80);
lv_obj_set_x( ui_Panel7, 5 );
lv_obj_set_y( ui_Panel7, -95 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel7, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel7, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel7, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel7, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel7, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel7, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel7, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel7, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel7, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label57 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label57, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label57, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label57, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label57,"Slayer 6");
lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel8, 120);
lv_obj_set_height( ui_Panel8, 80);
lv_obj_set_x( ui_Panel8, 140 );
lv_obj_set_y( ui_Panel8, -95 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel8, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel8, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel8, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel8, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel8, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel8, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel8, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel8, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel8, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label58 = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_Label58, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label58, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label58, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label58,"WE Pro 6");
lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel9, 120);
lv_obj_set_height( ui_Panel9, 80);
lv_obj_set_x( ui_Panel9, -129 );
lv_obj_set_y( ui_Panel9, 0 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel9, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel9, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel9, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel9, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel9, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel9, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel9, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel9, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel9, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label59 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label59, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label59, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label59, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label59,"Flat 9");
lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel10 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel10, 120);
lv_obj_set_height( ui_Panel10, 80);
lv_obj_set_x( ui_Panel10, 5 );
lv_obj_set_y( ui_Panel10, 0 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel10, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel10, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel10, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel10, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel10, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel10, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel10, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel10, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel10, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label60 = lv_label_create(ui_Panel10);
lv_obj_set_width( ui_Label60, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label60, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label60, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label60,"Slayer 9");
lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel11, 120);
lv_obj_set_height( ui_Panel11, 80);
lv_obj_set_x( ui_Panel11, 140 );
lv_obj_set_y( ui_Panel11, 0 );
lv_obj_set_align( ui_Panel11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel11, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel11, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel11, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel11, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel11, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel11, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel11, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel11, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel11, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel11, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label61 = lv_label_create(ui_Panel11);
lv_obj_set_width( ui_Label61, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label61, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label61, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label61,"WE Pro 9");
lv_obj_set_style_text_font(ui_Label61, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel12, 120);
lv_obj_set_height( ui_Panel12, 80);
lv_obj_set_x( ui_Panel12, -130 );
lv_obj_set_y( ui_Panel12, 95 );
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel12, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel12, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel12, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel12, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel12, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel12, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel12, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel12, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel12, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel12, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label62 = lv_label_create(ui_Panel12);
lv_obj_set_width( ui_Label62, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label62, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label62, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label62,"Londinium");
lv_obj_set_style_text_font(ui_Label62, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel13 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel13, 120);
lv_obj_set_height( ui_Panel13, 80);
lv_obj_set_x( ui_Panel13, 5 );
lv_obj_set_y( ui_Panel13, 95 );
lv_obj_set_align( ui_Panel13, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel13, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel13, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel13, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel13, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel13, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel13, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel13, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel13, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel13, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel13, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label63 = lv_label_create(ui_Panel13);
lv_obj_set_width( ui_Label63, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label63, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label63, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label63,"Leva X");
lv_obj_set_style_text_font(ui_Label63, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel14 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel14, 120);
lv_obj_set_height( ui_Panel14, 80);
lv_obj_set_x( ui_Panel14, 140 );
lv_obj_set_y( ui_Panel14, 95 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel14, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel14, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel14, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel14, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel14, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel14, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel14, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel14, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel14, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel14, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label64 = lv_label_create(ui_Panel14);
lv_obj_set_width( ui_Label64, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label64, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label64, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label64,"Cremina");
lv_obj_set_style_text_font(ui_Label64, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel15 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel15, 120);
lv_obj_set_height( ui_Panel15, 80);
lv_obj_set_x( ui_Panel15, -130 );
lv_obj_set_y( ui_Panel15, 190 );
lv_obj_set_align( ui_Panel15, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel15, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel15, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel15, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel15, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel15, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel15, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel15, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel15, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel15, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel15, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label65 = lv_label_create(ui_Panel15);
lv_obj_set_width( ui_Label65, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label65, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label65, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label65,"Turbo");
lv_obj_set_style_text_font(ui_Label65, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel16 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel16, 120);
lv_obj_set_height( ui_Panel16, 80);
lv_obj_set_x( ui_Panel16, 5 );
lv_obj_set_y( ui_Panel16, 190 );
lv_obj_set_align( ui_Panel16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel16, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel16, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel16, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel16, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel16, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel16, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel16, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel16, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel16, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel16, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label66 = lv_label_create(ui_Panel16);
lv_obj_set_width( ui_Label66, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label66, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label66, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label66,"Blooming");
lv_obj_set_style_text_font(ui_Label66, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel17 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel17, 120);
lv_obj_set_height( ui_Panel17, 80);
lv_obj_set_x( ui_Panel17, 140 );
lv_obj_set_y( ui_Panel17, 190 );
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel17, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel17, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel17, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel17, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x62D267), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_Panel17, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Panel17, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Panel17, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Panel17, lv_color_hex(0x3ED440), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Panel17, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Panel17, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label67 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label67, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label67, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label67, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label67,"Spro-Over");
lv_obj_set_style_text_font(ui_Label67, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label48 = lv_label_create(ui_ProfilesScreen);
lv_obj_set_width( ui_Label48, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label48, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label48, 203 );
lv_obj_set_y( ui_Label48, -155 );
lv_obj_set_align( ui_Label48, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label48,"Profile Name");
lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label48, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label48, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label48, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_ProfilesScreen);
lv_img_set_src(ui_Image2, &ui_img_espressoprofilepic_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 300
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 154
lv_obj_set_x( ui_Image2, 204 );
lv_obj_set_y( ui_Image2, 45 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label68 = lv_label_create(ui_ProfilesScreen);
lv_obj_set_width( ui_Label68, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label68, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label68, 200 );
lv_obj_set_y( ui_Label68, -210 );
lv_obj_set_align( ui_Label68, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label68,"Profiles");
lv_obj_set_style_text_color(ui_Label68, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label68, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label68, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label68, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label68, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label68, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button6 = lv_btn_create(ui_ProfilesScreen);
lv_obj_set_width( ui_Button6, 370);
lv_obj_set_height( ui_Button6, 80);
lv_obj_set_x( ui_Button6, 204 );
lv_obj_set_y( ui_Button6, 190 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x133964), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Button6, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0x246FC3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x5FE9F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Button6, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Button6, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Button6);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Select");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_ProfilesScreen);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 205 );
lv_obj_set_y( ui_Label6, -90 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6," This section will describe the selected profile,  \n explaining whether the profile is  interactive \n       or automated, and give information \n       regarding pressure and flow targets.");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel6, ui_event_Panel6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel7, ui_event_Panel7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel9, ui_event_Panel9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel10, ui_event_Panel10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel11, ui_event_Panel11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel12, ui_event_Panel12, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel13, ui_event_Panel13, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel14, ui_event_Panel14, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel15, ui_event_Panel15, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel16, ui_event_Panel16, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel17, ui_event_Panel17, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}
